[package]
name = "Artemos"
version = "0.1.0"
edition = "2024"
build = false

[dependencies]
sbi = { path = "./components/sbi" }
log = "0.4.26"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
buddy_system_allocator = "0.6"
xmas-elf = "0.7.0"
bitflags = "1.2.1"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers", rev = "4ee80e5" }
easy-fs = { path = "./easy-fs" }

[profile.release]
debug = true
opt-level = 0           # 优化级别,最低是0,最高是3, 0方便debug （最后可以删掉）
overflow-checks = false # 关闭整数溢出检查，方便debug（最后可以删掉）

[workspace]
members = ["components/*", "user", "easy-fs"]
exclude = ["easy-fs-fuse"]