[package]
name = "Artemos"
version = "0.1.0"
edition = "2024"

[dependencies]
sbi = { path = "./components/sbi"}
log = "0.4.26"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
buddy_system_allocator = "0.6"
bitflags = "1.2.1"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }

[workspace]
members = [
    "components/*",
    "user"
]
